import ProjectPicture1 from '../../../assets/images/pictures/projects/proj-1.webp';
import ProjectPicture2 from '../../../assets/images/pictures/projects/proj-2.webp';
import ProjectPicture3 from '../../../assets/images/pictures/projects/proj-3.webp';
import ProjectPicture4 from '../../../assets/images/pictures/projects/proj-4.webp';
import ProjectPicture5 from '../../../assets/images/pictures/projects/proj-5.webp';
import ProjectPicture6 from '../../../assets/images/pictures/projects/proj-6.webp';

export const ProjectCardData = [
  {id: 1, src: `${ProjectPicture1}`, alt: 'Project Picture 1', title: 'Project Tile goes here and wiil be looking good', mainText: 'This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content and you can see how webkit cut extra lines', stackSpanText: 'Tech stack :', stackText: 'HTML , JavaScript, SASS, React, Redux Toolkit, React Router', chainLinkText: 'Live Preview', githubLinkText: 'View Code', chainLink: '#', githubLink: '#'},
  {id: 2, src: `${ProjectPicture2}`, alt: 'Project Picture 2', title: 'Project Tile goes here', mainText: 'This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content', stackSpanText: 'Tech stack :', stackText: 'HTML , JavaScript, SASS, React', chainLinkText: 'Live Preview', githubLinkText: 'View Code', chainLink: '#', githubLink: '#'},
  {id: 3, src: `${ProjectPicture3}`, alt: 'Project Picture 3', title: 'Project Tile goes here', mainText: 'This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content', stackSpanText: 'Tech stack :', stackText: 'HTML , JavaScript, SASS, React', chainLinkText: 'Live Preview', githubLinkText: 'View Code', chainLink: '#', githubLink: '#'},
  {id: 4, src: `${ProjectPicture4}`, alt: 'Project Picture 4', title: 'Project Tile goes here', mainText: 'This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content', stackSpanText: 'Tech stack :', stackText: 'HTML , JavaScript, SASS, React', chainLinkText: 'Live Preview', githubLinkText: 'View Code', chainLink: '#', githubLink: '#'},
  {id: 5, src: `${ProjectPicture5}`, alt: 'Project Picture 5', title: 'Project Tile goes here', mainText: 'This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content', stackSpanText: 'Tech stack :', stackText: 'HTML , JavaScript, SASS, React', chainLinkText: 'Live Preview', githubLinkText: 'View Code', chainLink: '#', githubLink: '#'},
  {id: 6, src: `${ProjectPicture6}`, alt: 'Project Picture 6', title: 'Project Tile goes here', mainText: 'This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content', stackSpanText: 'Tech stack :', stackText: 'HTML , JavaScript, SASS, React', chainLinkText: 'Live Preview', githubLinkText: 'View Code', chainLink: '#', githubLink: '#'},
]